export const NAVIGATOR = {
    START: 'NAVIGATOR_START',
    LOGIN: 'NAVIGATOR_LOGIN',
    DRAWER: 'NAVIGATOR_DRAWER'
};
const LOGIN_STACK = {
    LOGIN_LANDING: 'LOGIN_LANDING',
    LOGIN: 'LOGIN',
    REGISTER: 'REGISTER',
    PASSWORD_RECOVERY: 'PASSWORD_RECOVERY',
};
const LANDING_STACK = {
    PROFILE: 'PROFILE',
    PROPERTIES: 'PROPERTIES',
    HOME: 'HOME',
    INMOBILIARIA_HOME:'INMOBILIARIA_HOME',
};
const PROPERTIES_STACK = {
    TOREGISTER: 'TOREGISTER',
    MYPROPERTIES: 'MYPROPERTIES',
    PROPPERTIES: 'PROPERTIES',
    PROPPERTIES_VIEW: 'PROPPERTIES_VIEW',
    PROPPERTIES_UPDATE: 'PROPPERTIES_UPDATE',
};
const TAB_STACK = {
    INMOBILIARIA: 'INMOBILIARIA',
    FAVORITES: 'TAB_FAVORITES',
    PROFILE: 'TAB_PROFILE',
};
const DRAWER_SCREEN = {
    PROFILE: 'PROFILE',
};
const PROFILE_STACK = {
    PROFILE_MAIN: 'PROFILE_MAIN',
    SETTINGS: 'SETTINGS',
    COMENTS: 'COMENTS',
    CHANGE_PASWORD: 'CHANGE_PASWORD'
};
export default {
    NAVIGATOR,
    LOGIN_STACK,
    LANDING_STACK,
    PROPERTIES_STACK,
    TAB_STACK,
    DRAWER_SCREEN,
    PROFILE_STACK
};